# Generated by Django 4.2 on 2024-09-08 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_slots_user_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="table",
        ),
    ]
