# Generated by Django 4.2 on 2024-08-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_notifications_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="Event",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app.event",
            ),
            preserve_default=False,
        ),
    ]
