# Generated by Django 4.2 on 2024-08-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_notifications_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="Event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.event"
            ),
        ),
    ]
