# Generated by Django 4.2 on 2024-09-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_event_event_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="completedEvents",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("excel", models.FileField(upload_to="excelSheets/")),
                ("event_id", models.IntegerField()),
                ("host", models.CharField(max_length=100)),
                ("Event_name", models.CharField(max_length=150)),
                ("members", models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
