# Generated by Django 4.2 on 2024-09-11 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0007_completedevents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currentevent",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="Event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="app.event"
            ),
        ),
        migrations.AlterField(
            model_name="slots",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
