# Generated by Django 4.2 on 2024-09-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_currentevent_user_alter_notifications_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.IntegerField(unique=True)),
                ("table", models.JSONField()),
            ],
        ),
    ]
