# Generated by Django 4.2 on 2024-10-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_realtable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
