# Generated by Django 4.2 on 2024-10-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_notifications_create_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalSlotsTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "excel_file_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.event"
                    ),
                ),
            ],
        ),
    ]
