# Generated by Django 4.2 on 2024-10-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_finalslotstable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finalslotstable",
            name="excel_file_path",
        ),
        migrations.AddField(
            model_name="finalslotstable",
            name="excel_file",
            field=models.FileField(
                blank=True, null=True, upload_to="excelSheets/finaltable/"
            ),
        ),
    ]
