# Generated by Django 4.2 on 2024-10-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_finalslotstable_excel_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="tablemodifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table", models.JSONField()),
                ("changes", models.CharField(max_length=800)),
                (
                    "Event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.event"
                    ),
                ),
            ],
        ),
    ]
