# Generated by Django 4.2 on 2024-11-01 20:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_tablemodifications_changes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedevents",
            name="excel",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="Excel Sheets"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="Event_Thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="EventPhotos/def2.webp",
                max_length=255,
                null=True,
                verbose_name="Event Photos",
            ),
        ),
        migrations.AlterField(
            model_name="finalslotstable",
            name="excel_file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Final Table"
            ),
        ),
    ]
