# Generated by Django 4.2 on 2024-11-01 21:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_alter_completedevents_excel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="Event_Thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="EventPhotos/xbod0lsndky4qwkpswcp",
                max_length=255,
                null=True,
                verbose_name="EventPhotos",
            ),
        ),
    ]
