# Generated by Django 4.2 on 2024-11-01 21:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_alter_event_event_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="Event_Thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="EventPhotos/xbod0lsndky4qwkpswcp",
                max_length=255,
                null=True,
                verbose_name="Event Photos",
            ),
        ),
    ]
