# Generated by Django 4.2 on 2025-03-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_alter_event_event_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedevents",
            name="excel",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="finalslotstable",
            name="excel_file",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
